services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: giga_server
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - GIN_MODE=release
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:14-alpine
    container_name: giga_postgres
    user: postgres
    ports:
      - 5555:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
